<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXxc7xot\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXxc7xot/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerXxc7xot.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerXxc7xot\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerXxc7xot\appProdProjectContainer([
    'container.build_hash' => 'Xxc7xot',
    'container.build_id' => 'f7b0c49d',
    'container.build_time' => 1605907507,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXxc7xot');
